services:
  # ────────────────────────────────────────────────────
  # PostgreSQL
  # ────────────────────────────────────────────────────
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: airguardian
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # ────────────────────────────────────────────────────
  # Redis (broker & backend for Celery)
  # ────────────────────────────────────────────────────
  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

  # ────────────────────────────────────────────────────
  # FastAPI application (uvicorn)
  # ────────────────────────────────────────────────────
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    command: >
      sh -c "alembic upgrade head &&
             uvicorn app.main:app --reload --host 0.0.0.0 --port 8000"

  # ────────────────────────────────────────────────────
  # Celery worker
  # ────────────────────────────────────────────────────
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    env_file:
      - .env
    depends_on:
      - redis
      - postgres
    command: celery -A app.celery.celery_app worker --loglevel=info

  # ────────────────────────────────────────────────────
  # Celery beat (scheduler)
  # ────────────────────────────────────────────────────
  beat:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    env_file:
      - .env
    depends_on:
      - redis
      - postgres
    command: celery -A app.celery.celery_app beat --loglevel=info

volumes:
  postgres_data:
  redis_data:

