"""init

Revision ID: 72ffa503a104
Revises: 
Create Date: 2025-07-21 19:27:14.234658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72ffa503a104'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('social_security_number', sa.String(), nullable=False),
    sa.Column('purchased_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('x', sa.Integer(), nullable=False),
    sa.Column('y', sa.Integer(), nullable=False),
    sa.Column('z', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nfz_active',
    sa.Column('drone_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['drone_id'], ['drones.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ),
    sa.PrimaryKeyConstraint('drone_id')
    )
    op.create_index(op.f('ix_nfz_active_drone_id'), 'nfz_active', ['drone_id'], unique=False)
    op.create_table('violations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('drone_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('x', sa.Integer(), nullable=False),
    sa.Column('y', sa.Integer(), nullable=False),
    sa.Column('z', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['drone_id'], ['drones.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('violations')
    op.drop_index(op.f('ix_nfz_active_drone_id'), table_name='nfz_active')
    op.drop_table('nfz_active')
    op.drop_table('drones')
    op.drop_table('owners')
    # ### end Alembic commands ###
