"""create violations and nfz_active tables

Revision ID: a8a763b272b2
Revises: 
Create Date: 2025-07-18 09:32:59.378719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8a763b272b2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nfz_active',
    sa.Column('drone_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('drone_id')
    )
    op.create_index(op.f('ix_nfz_active_drone_id'), 'nfz_active', ['drone_id'], unique=False)
    op.create_table('violations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('drone_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('z', sa.Float(), nullable=False),
    sa.Column('owner_first', sa.String(), nullable=False),
    sa.Column('owner_last', sa.String(), nullable=False),
    sa.Column('owner_ssn', sa.String(), nullable=False),
    sa.Column('owner_phone', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('violations')
    op.drop_index(op.f('ix_nfz_active_drone_id'), table_name='nfz_active')
    op.drop_table('nfz_active')
    # ### end Alembic commands ###
